### ISSUE TITLE
Possible incompatibility with Windows Server 2022

### ISSUE THREAD

**Issue by unquietwiki** [ltb-project/self-service-password#918] opened 2024-06-18 15:48 UTC
Hey all. Currently having trouble authenticating against Active Directory on a Windows Server 2022 instance; worked with a previous 2012 instance. Using "openssl s_client" to poll the LDAPS port, I was getting a TLS v1.3 response; figured that was an issue, so I [disabled it](https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/how-to-disable-tls-1-3-for-ad-and-ldap). However, while I'm getting a TLS v1.2 response now, I think it's still not matching the ciphers being used by the server.

```
Requested Signature Algorithms: RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1:RSA+SHA512:ECDSA+SHA512
Shared Requested Signature Algorithms: RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:ECDSA+SHA256:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512
```

Currently using version 1.6 of SSP on Debian Bookworm. Thanks!

**Comment by coudot** [comment] 2024-06-19 08:38
I don't see why you disable TLSv1.3.

Configure your SSL layer on your server to match ciphers from AD. This is not linked to Self Service Password.

Try to connect to AD with openssl s_client

**Comment by unquietwiki** [comment] 2024-06-20 02:02
@coudot Thank you for clarifying the issue wasn't TLS 1.3; that was something I know is an issue with a lot of software out there. Is there good documentation or code reference regarding getting SSP to use whatever TLS ciphers Windows is trying to use? I saw some documentation, but it was pretty sparse.

**Comment by coudot** [comment] 2024-06-20 05:44
I don't know what is the correct SSL configuration for Windows. The SSL settings are outside Self Service Password configuration, but you can override system settings by putting this on your config file:
```php
putenv("LDAPTLS_CIPHER_SUITE=HIGH:MEDIUM");
```
Check the documentation of OpenSSL for correct configuration of cipher suite.

**Comment by unquietwiki** [comment] 2024-06-20 06:38
Thank you for that. Running into a completely different issue now: it's saying my new password is "insufficient quality". Using same complexity rules I had in SSP 1.5; guess that's a separate issue altogether.

BTW, I truly appreciate your prompt responses on this stuff; it helps!

**Comment by unquietwiki** [comment] 2024-06-24 21:28
@coudot wanted to give you an update. I rebuilt the config file against the new version, and then began tweaking things.

- "insufficient quality" error went away when I used the default password restrictions; there may be an issue there I can report in a separate post.
- Since this is an AD environment, I had to delegate the service account to reset + create/delete both regular and inetOrg users to get rid of error 50 messages. You may have run into that as a separate issue before.
- If I set the program to try calling port LDAPS/636 on one server, and LDAP/389 on another, it appears to skip using the LDAPS server, and respond against the LDAP server. It will also refuse to reset the password in this configuration. If I set it to just use the LDAPS server alone, it will come back with an LDAP error.
- Using the "putenv" you provided, as well as changing it to the requested cipher suite, appears to have no effect on the LDAP error.

Below is the full error message I get from Nginx's error log. The audit.log file has a much more truncated "ldaperror" message that doesn't say what the exact issue is.

`2024/06/24 21:14:01 [error] 643334#643334: *2344 FastCGI sent in stderr: "PHP message: Module Zxcvbn successfully loaded; PHP message: PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/share/self-service-password/vendor/ltb-project/ldap/src/Ltb/PhpLDAP.php on line 36; PHP message: LDAP - Bind error -1  (Can't contact LDAP server); PHP message: PHP Deprecated:  Creation of dynamic property Smarty_Internal_Template::$compiled is deprecated in /usr/share/php/smarty3/sysplugins/smarty_internal_template.php on line 719; PHP message: PHP Deprecated:  Creation of dynamic property Smarty_Internal_Template::$compiled is deprecated in /usr/share/php/smarty3/sysplugins/smarty_internal_template.php on line 719; PHP message: PHP Deprecated:  Creation of dynamic property Smarty_Internal_Template::$compiled is deprecated in /usr/share/php/smarty3/sysplugins/smarty_internal_template.php on line 719; PHP message: PHP Deprecated:  Creation of dynamic property Smarty_Internal_Template::$compiled is deprecated in /usr/share/php/smarty3/sysplugins/smarty_internal_template.php on line 719; PHP message: PHP Warning:  Undefined array key "msg_changehelpextramessage" in /var/cache/self-service-password/templates_c/f6b50b13b91599a6d59a20cb1147ad5af3c8d817_2.file.change.tpl.php on line 43; PHP message: PHP Warning:  Attempt to read property "value" on null in /var/cache/self-service-password/templates_c/f6b50b13b91599a6d59a20cb1147ad5af3c8d817_2.file.change.tpl.php on line 43; PHP message: PHP Deprecated:  Creation of dynamic property Smarty_Internal_Template::$compiled is deprecated in /usr/share/php/smarty3/sysplugins/smarty_internal_template.php on line 719; PHP message: PHP Deprecated:  Creation of dynamic property Smarty_Internal_Template::$compiled is deprecated in /usr/share/php/smarty3/sysplugins/smarty_internal_template.php on line 719; PHP message: PHP Deprecated:  Creation of dynamic property Smarty_Internal_Template::$compiled is deprecated in /usr/share/php/smarty3/sysplugins/smarty_intern`

**Comment by coudot** [comment] 2024-06-29 11:51
> "insufficient quality" error went away when I used the default password restrictions; there may be an issue there I can report in a separate post.

I don't understand where is the issue. If you provide a low quality password to AD, it will be refused.

> Since this is an AD environment, I had to delegate the service account to reset + create/delete both regular and inetOrg users to get rid of error 50 messages. You may have run into that as a separate issue before.

This is written in documentation https://self-service-password.readthedocs.io/en/stable/config_ldap.html#active-directory

> If I set the program to try calling port LDAPS/636 on one server, and LDAP/389 on another, it appears to skip using the LDAPS server, and respond against the LDAP server. It will also refuse to reset the password in this configuration. If I set it to just use the LDAPS server alone, it will come back with an LDAP error.

Because your SSL configuration is not correct. SSL is required by AD to change password. No issue here.

> Using the "putenv" you provided, as well as changing it to the requested cipher suite, appears to have no effect on the LDAP error.

You need to find the expected values for you Active Directory

**Comment by unquietwiki** [comment] 2024-06-30 00:59
Thank you for the follow-up on this. I see in the documentation that there were additional delegate rules I should have in place; I will make that correction on my end. And sorry if I wasn't more clear on the 636/389 error: I understand its correct behavior, and was intending to highlight that the LDAPS connectivity was still being refused.

Regarding the low-quality password error, it was occurring before submitting to LDAP; it seemed to be based on the PHP logic that was checking password quality against the configured rules, and setting the limits in the config file to "0" nullified the error. I had rules in place with version 1.5, so I'm curious why it'd be an issue now.

Returning to the original LDAPS error, it's certainly not generating an extended error message (and I do have that enabled in the config), as the code indicates I should be getting. If I could get it to tell me exactly why the cert connection isn't working, then it'd be easier to troubleshoot this problem. I might dig around the code some and see if there's a way to better express the exact error return.

**Comment by coudot** [comment] 2024-06-30 15:27
> Regarding the low-quality password error, it was occurring before submitting to LDAP; it seemed to be based on the PHP logic that was checking password quality against the configured rules, and setting the limits in the config file to "0" nullified the error. I had rules in place with version 1.5, so I'm curious why it'd be an issue now.

Indeed, if there is a behavior change between 1.5 and 1.6, it could be a bug. Be sure to use the correct config.inc.php from the package and use config.inc.local.php for your settings.

> Returning to the original LDAPS error, it's certainly not generating an extended error message (and I do have that enabled in the config), as the code indicates I should be getting. If I could get it to tell me exactly why the cert connection isn't working, then it'd be easier to troubleshoot this problem. I might dig around the code some and see if there's a way to better express the exact error return.

First check with openssl s_client that you can connect to AD, and verify the certificate chain.

**Comment by unquietwiki** [comment] 2024-07-02 21:12
Exported the CA cert to a PEM file, and ran **openssl s_client -CAfile** ...

```
CONNECTED(00000003)
---
Certificate chain
 0 s:
   i:DC = loc, DC = redacted, CN = CIUSSJCA01
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jun 18 00:46:55 2024 GMT; NotAfter: Jun 18 00:46:55 2025 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
REDACTED
-----END CERTIFICATE-----
subject=
issuer=DC = loc, DC = redacted, CN = CIUSSJCA01
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1:RSA+SHA512:ECDSA+SHA512
Shared Requested Signature Algorithms: RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:ECDSA+SHA256:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: ECDH, secp384r1, 384 bits
---
SSL handshake has read 2042 bytes and written 497 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: B11C000008A62D2540D7EC149FEB5027080C6F4B45EF4C91574CDF4391A79E06
    Session-ID-ctx: 
    Master-Key: 71D15B4CCB1BEE2AEA1931962C346789FA3A15A8E6C18089CBBDE3F53E04200826CBF6EDED6D665A8CC6DFA9523969A6
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1719954538
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---

```

**Comment by coudot** [comment] 2024-07-03 08:25
So configure this CA cert on your system so that PHP will trust it

**Comment by unquietwiki** [comment] 2024-07-03 17:41
Okay...

1. Dropped the CA into **/usr/local/share/ca-certificates** as a .crt file.
2. Ran **update-ca-certificates -v -f** to ensure the CA was loaded properly.
3. Checked the OpenSSL cipher list with **openssl ciphers -v TLSv1.2**
4. Verified the cert was actually loaded into **/etc/ssl/certs/ca-certificates.crt** by step 2.
5. The following below is in **/etc/ldap/ldap.conf** , and I also added as putenv variables to **config.inc.local.php**

```
TLS_CACERT      /etc/ssl/certs/ca-certificates.crt
TLS_REQCERT     allow
TLS_CIPHER_SUITE TLSv1.2
```


Unfortunately, I still get an "LDAP error" when attempting to reset the password.

**Comment by unquietwiki** [comment] 2024-07-17 21:25
@coudot Hey, think I found a workaround/fix for this, that you might want to add to your documentation. Per [this obscure PHP comment](https://www.php.net/manual/en/function.ldap-bind.php#118543), it turns out that LDAP(S) is still requiring old ciphers; I noticed a hint of that in some of the debugging tools I used for verifying that LDAPS worked (ldapsearch wasn't having much luck, but other tooling prevailed). The following is what I now have at the top of my **config.inc.local.php** file.

```
putenv('LDAPTLS_CIPHER_SUITE=NORMAL:!VERS-TLS1.2');
putenv('LDAPTLS_REQCERT=allow');
putenv('LDAPTLS_CACERT=/etc/ssl/certs/ca-certificates.crt');

```

**Comment by davidcoutadeur** [comment] 2024-07-18 07:37
Could you try with this instead?

```
putenv('LDAPTLS_CIPHER_SUITE=NORMAL:!VERS-TLS1.2');
putenv('LDAPTLS_REQCERT=demand');
putenv('LDAPTLS_CACERT=/etc/ssl/certs/ca-certificates.crt');
```

The aim is to understand if the problem is really the cipher suite.

**Comment by unquietwiki** [comment] 2024-07-20 02:58
@davidcoutadeur Sorry for the delayed response. So setting REQCERT to "demand" caused LDAP failure. I then set it back to "allow" and disabled the CIPHER_SUITE env; also failure. Having "allow" and the CIPHER_SUITE I found on that PHP comment works fine.

**Comment by davidcoutadeur** [comment] 2024-07-22 08:37
Ok, so it does not seem to be a problem with self-service-password, but rather a TLS configuration.

TLS configuration occurs in ldap library (usually /etc/ldap/ldap.conf or /etc/openldap/ldap.conf), so I don't think there is any issue for self-service-password there.

If your problem is solved, I am closing this ticket

**Comment by unquietwiki** [comment] 2024-07-22 16:15
@davidcoutadeur Thanks for reviewing this. I do request that your documentation get updated with these findings, as able: I don't recall mention of the use of env variables, and that particular cipher was apparently necessary for it to work with the 2022 server.

**Comment by davidcoutadeur** [comment] 2024-07-22 16:22
Actually, you shouldn't need to use putenv in your configuration file.

Configuring your ldap.conf should be sufficient.

I reopen the issue to let you the opportunity to provide evidence that the ldap.conf configuration is not sufficient. Especially, take care that the ldap.conf path could be different depending on your operating system, php configuration,...

**Comment by unquietwiki** [comment] 2024-07-23 00:41
@davidcoutadeur I disabled the env settings & adjusted the **/etc/ldap/ldap.conf** file with the updated value set. With **NORMAL:!VERS-TLS1.2** as the TLS_CIPHER_SUITE, the application continues to function.

**Comment by davidcoutadeur** [comment] 2024-07-23 07:53
Ok, thanks for the feedback. So the documentation is accurate.

The last step for you is to find a way to upgrade the TLS version of Active Directory to 1.2 or 1.3. Maybe is it only a configuration issue, because TLS 1.3 seems supported in Windows Server 2022.

**Closed by davidcoutadeur** 2024-07-23 07:53 UTC
Labels: question

**Comment by unquietwiki** [comment] 2024-07-23 19:37
@davidcoutadeur That's the funny part. I started off with 1.3 being default on 2022, but then downgraded TLS to 1.2 when I started having this issue. And when I do an SSL/TLS lookup on the server, I do get a TLS 1.2 response. It's just that LDAPS appears to require the older cipher, and not the default TLS 1.2/1.3 ciphers. I didn't run into this situation when I was polling against a 2012 Server I've since deprecated.

I guess based on all of this, my ask would be that the other cipher be listed as a failover option, and also the part about loading in the CA cert correctly (I think you all are referring to some old Java instructions in the documentation).

**Comment by davidcoutadeur** [comment] 2024-07-24 07:55
I think the documentation is quite exhaustive on this issue: https://self-service-password.readthedocs.io/en/stable/config_ldap.html#server-address

We can't list all TLS configuration possibilities, as it it depends on many factors and configuring TLS ciphers is already well documented by the TLS library vendors.

**Comment by unquietwiki** [comment] 2024-07-24 14:07
@davidcoutadeur Acknowledged. Well, thank you for your help on sorting this out!
