### ISSUE TITLE
Posthook does not work with apostrophes

### ISSUE THREAD

**Issue by coudot** [ltb-project/self-service-password#33] opened 2016-10-04 15:18 UTC
See http://tools.ltb-project.org/issues/844

**Comment by coudot** [comment] 2016-10-04 15:52
I cannot reproduce the bug.

**Comment by Tangresh** [comment] 2016-12-06 15:44
I am not able to reproduce it either. I guess this can be closed...

**Comment by plewin** [comment] 2016-12-06 15:52
Please don't close it yet, I agree there might be a bug in the posthook
feature.

**Comment by plewin** [comment] 2016-12-06 17:44
I reproduced the bug and OP's patch is solving the issue.
Passwords with spaces, " or ' make the posthook command receive wrong arguments (incorrects or wrong number of arguments).

[my test files](https://gist.github.com/plewin/549d889dcee14315fa3a984d8d4c06bc)

**Comment by coudot** [comment] 2016-12-07 08:54
Thanks @plewin for the patch

**Closed** 2016-12-07 08:53 UTC
Labels: invalid
