### ISSUE TITLE
installing on a redhat server 

### ISSUE THREAD

**Issue by Verakhs** [ltb-project/self-service-password#368] opened 2020-01-24 20:10 UTC
Hello people, 

I am trying to use this joined with a Openldap. 

I have tried my best to install it with no luck. 

The first step, I do this 

 $ rpm --import https://ltb-project.org/wiki/lib/RPM-GP                            

and I got error

 G-KEY-LTB-project
curl: (35) TCP connection reset by peer
error: https://ltb-project.org/wiki/lib/RPM-GPG-KEY-LTB-project: import read fai                             led(2).

I thought it maybe better to download the rpm and then run it locally 
I downloaded the "self-service-password-1.3-1.el7.noarch" 
Then I ran the following 

# yum localinstall self-service-password-1.3-1.el7.noarch.rpm
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
Examining self-service-password-1.3-1.el7.noarch.rpm: self-service-password-1.3-1.el7.noarch
self-service-password-1.3-1.el7.noarch.rpm: does not update installed package.
Nothing to do

Thanks for any help

**Comment by coudot** [comment] 2020-01-27 06:47
Duplicate of #324

**Closed by coudot** 2020-01-27 06:47 UTC
