### ISSUE TITLE
in mater version ,syntax error, unexpected '[' in phar:///usr/share/self-service-password/lib/vendor/defuse-crypto.phar/src/RuntimeTests.php on line 110

### ISSUE THREAD

**Issue by dusansheng** [ltb-project/self-service-password#267] opened 2019-02-22 04:29 UTC

**Comment by plewin** [comment] 2020-01-27 12:13
Hi @dusansheng sorry I know it's a old thread. Did you solve your issue ?

The error message sounds like php version is < 5.4. Is it possible you are running an unsupported php version ? If you are running centos 6, the issue will be solved by upgrading to centos 7 which has a newer php version.

**Comment by plewin** [comment] 2020-03-14 07:43
Closing this because the issue is not reproducible on supported php versions.

If anybody else have this issue you are likely running php 5.3 or less, please upgrade to a supported php version.

**Closed by plewin** 2020-03-14 07:43 UTC
Labels: question
