### ISSUE TITLE
Some bug in the posthook script? Or am I missing something?

### ISSUE THREAD

**Issue by aleguedes1983** [ltb-project/self-service-password#151] opened 2017-09-12 22:49 UTC
Hi all, congratulations for this tool. I have been using it for some years, and now I am upgrading it.

I am very interest in the feature to run a posthook when the password is changed, but I do not know why it is not working.

I've set correctly the config.inc.php pointing to the script file, exactly the same way described in the documentation:

`$posthook = "/usr/share/self-service-password/posthook.sh";`

In the script, I have:
```
#!/bin/bash

LOGIN=$1
NEWPASSWORD=$2
OLDPASSWORD=$3

echo `date` >> /tmp/posthook.log
echo "$LOGIN / $NEWPASSWORD / $OLDPASSWORD" >> /tmp/posthook.log
```
If I run manually, I can see some information in the log file, but using the WebPage, anything seems to happen.

I've set the script group and owner to the apache user, also, the log file.
i've checked if my PHP was is some configuration that was preventing the apache execute the script, and it is OK.

Just to let you know, the OpenLDAP password is changed successfully using the user interface, and the mail token as well.

Is there some special trick that is not detailed in the documentation that I am need to validate? Or even, a bug?

My environment is:

```
SSP installed: self-service-password-1.1-1.el7.noarch.rpm
[root@awsvirprolapp01 self-service-password]# httpd -v
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built:   May  9 2017 11:21:32

[root@awsvirprolapp01 self-service-password]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)

[root@awsvirprolapp01 self-service-password]# php -v
PHP 5.4.16 (cli) (built: Aug  5 2016 07:50:38)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```

Thank you

**Comment by coudot** [comment] 2017-09-13 06:48
If SELinux is enabled, then you need to give correct permission to the script.

Read for example https://serverfault.com/questions/642353/selinux-interfering-with-apache-php#642355

**Comment by aleguedes1983** [comment] 2017-09-13 14:11
Hi @coudot 

Thank you for the fast answer. Well, the SELinux was disabled. I'v e checked it

```
[root@awsvirprolapp01 log]# sestatus
SELinux status:                 disabled
```
Some other idea?

Do you have some other version that I could test here? I've downloaded the current master version from the repository, but seems that it has some other bugs.

Thx

**Comment by plewin** [comment] 2017-09-13 14:17
Have you checked the logs with $debug = true? php normally logs when this
function does not work or is disabled

**Comment by aleguedes1983** [comment] 2017-09-13 15:30
Hi @plewin 
Yes, I've enabled it, and any error message is displayed in the logs, screens or WebPage. Just the normal logs. Seems that the change.php page does not reach the script.

Also, I've tried to use another script to touch some other information....changed the PHP code to use shell_exec....etc...  no luck.

I've installed now the version self-service-password-1.0-2.el7.noarch.rpm (I used the same config file of the version 1.1-1. The problem still happening... =/

My config can be found here: https://pastebin.com/fVvNDVyn

Thank you very much.

**Comment by plewin** [comment] 2017-09-13 16:55
I could not reproduce your problem, posthook works on my side in a similar fresh environment.

Can you double check if your script is really marked as executable for apache ? 

```
ls -la /usr/share/self-service-password/posthook.sh
sudo chmod +x /usr/share/self-service-password/posthook.sh
ls -la /usr/share/self-service-password/posthook.sh
```

**Comment by plewin** [comment] 2017-10-12 20:04
Hi @aleguedes1983,
Have you found a solution to your problem ?

**Comment by aleguedes1983** [comment] 2017-10-13 01:19
Hi @plewin.

Nope, I was not able to realize where the problem is, so I still using the version where I've changed the php code to call the external script, and change an ActiveDirectory password as well.

It have been working well for +2 years.  I will try again when a new SSP be available.

May this ticket can be closed.

Thank you,

**Closed** 2017-10-13 01:19 UTC
Labels: question
