### ISSUE TITLE
Adding option to simply unlock active directory accounts 

### ISSUE THREAD

**Issue by Loiseau2nuit** [ltb-project/self-service-password#786] opened 2023-07-11 13:35 UTC
Hi,

As discussed in thread #785, a feature to let users simply unlock their AD accounts without having to reset their password, would be really appreciated.

Thanks in advance

**Comment by coudot** [comment] 2023-07-15 09:20
Seems a duplicate of #122

**Closed** 2023-07-15 09:20 UTC
Labels: duplicate
