### ISSUE TITLE
Debian9 aka stretch packages

### ISSUE THREAD

**Issue by sgargel** [ltb-project/self-service-password#120] opened 2017-06-20 09:34 UTC
Can you provide repository and packages for the new debian stable release (stretch)?

**Comment by coudot** [comment] 2017-06-21 08:29
You should be able to use the latest debian package in stretch. Did you try?

**Comment by sgargel** [comment] 2017-06-21 09:55
The package was already installed but after upgrade from jessie to stretch i get this:

<pre>
root@VT-LNXPWD01:~# apt-key list 
/etc/apt/trusted.gpg
--------------------
pub   dsa1024 2009-07-02 [SC]
      3FC3 FD92 ABA3 975D 2BEB  95A7 0AC5 1F92 6D45 BFC5
uid           [ unknown] Clement OUDOT (LTB-project) <clem.oudot@gmail.com>
sub   elg2048 2009-07-02 [E]
</pre>

<pre>
root@VT-LNXPWD01:~# apt-get update; apt-get upgrade
Ign:2 http://ftp.it.debian.org/debian stretch InRelease
Trovato:3 http://security.debian.org stretch/updates InRelease
Trovato:4 http://ftp.it.debian.org/debian stretch-updates InRelease
Trovato:5 http://ftp.it.debian.org/debian stretch Release
Trovato:1 https://ltb-project.org/debian/jessie jessie InRelease
Err:1 https://ltb-project.org/debian/jessie jessie InRelease
  Le seguenti firme non erano valide: 3FC3FD92ABA3975D2BEB95A70AC51F926D45BFC5
Lettura elenco dei pacchetti... Fatto
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://ltb-project.org/debian/jessie jessie InRelease: Le seguenti firme non erano valide: 3FC3FD92ABA3975D2BEB95A70AC51F926D45BFC5
W: Impossibile recuperare http://ltb-project.org/debian/jessie/dists/jessie/InRelease  Le seguenti firme non erano valide: 3FC3FD92ABA3975D2BEB95A70AC51F926D45BFC5
W: Impossibile scaricare alcuni file di indice: saranno ignorati o verranno usati quelli vecchi.
</pre>

**Comment by coudot** [comment] 2017-06-21 12:41
Strange, I don't have this error from a jessie box.

On server, reprepro says all is ok:
```
$ reprepro list jessie
jessie|main|amd64: berkeleydb-ltb 4.6.21.NC-4-patch4
jessie|main|amd64: openldap-ltb 2.4.45.1
jessie|main|amd64: openldap-ltb-check-password 2.4.45.1
jessie|main|amd64: openldap-ltb-contrib-overlays 2.4.45.1
jessie|main|amd64: openldap-ltb-dbg 2.4.45.1
jessie|main|amd64: openldap-ltb-mdb-utils 2.4.45.1
jessie|main|amd64: openldap-ltb-ppm 2.4.45.1
jessie|main|amd64: self-service-password 1.0-2
jessie|main|amd64: white-pages 0.1-1
jessie|main|source: openldap-ltb 2.4.45.1
```

**Comment by plewin** [comment] 2017-06-21 13:18
I checked manually the file http://ltb-project.org/debian/jessie/dists/jessie/InRelease and the public key 0x3FC3FD92ABA3975D2BEB95A70AC51F926D45BFC5 does verify the signature.

Is there a chance that a bad proxy is between your server and the repo server ?
Perhaps switching the repo in /etc/apt/sources.list.d/ltb-project.list to https or looking at curl -L http://ltb-project.org/debian/jessie/dists/jessie/InRelease to see if it looks like a pgp signed message can help

**Comment by coudot** [comment] 2017-06-21 13:59
I have done a reprepro export to regenerate signature, could you check again!

**Comment by plewin** [comment] 2017-06-21 14:31
When manually checked, signatures still look fine.

I reproduced the problem, I am trying to understand it.
```
vagrant@stretch:~$ wget -O - http://ltb-project.org/wiki/lib/RPM-GPG-KEY-LTB-project | sudo apt-key add -
--2017-06-21 14:25:29--  http://ltb-project.org/wiki/lib/RPM-GPG-KEY-LTB-project
Resolving ltb-project.org (ltb-project.org)... 163.172.47.55
Connecting to ltb-project.org (ltb-project.org)|163.172.47.55|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://ltb-project.org/wiki/lib/RPM-GPG-KEY-LTB-project [following]
--2017-06-21 14:25:30--  https://ltb-project.org/wiki/lib/RPM-GPG-KEY-LTB-project
Connecting to ltb-project.org (ltb-project.org)|163.172.47.55|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ltb-project.org/lib/RPM-GPG-KEY-LTB-project [following]
--2017-06-21 14:25:30--  https://ltb-project.org/lib/RPM-GPG-KEY-LTB-project
Reusing existing connection to ltb-project.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 1706 (1.7K)
Saving to: ÔÇÿSTDOUTÔÇÖ

-                             100%[=================================================>]   1.67K  --.-KB/s    in 0s

2017-06-21 14:25:30 (102 MB/s) - written to stdout [1706/1706]

OK
vagrant@stretch:~$ sudo apt-get update
Ign:1 http://deb.debian.org/debian stretch InReleaset Text  ^T To Spell    ^_ Go To Line  ^V Next Page   M-/ Last Line
Hit:2 http://deb.debian.org/debian stretch Release
Get:3 http://security.debian.org/debian-security stretch/updates InRelease [62.9 kB]
Get:6 http://security.debian.org/debian-security stretch/updates/main Sources [24.0 kB]
Get:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [43.7 kB]
Reading package lists... Done
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
vagrant@stretch:~$ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 170 kB of archives.
After this operation, 242 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 apt-transport-https amd64 1.4.6 [170 kB]
Fetched 170 kB in 0s (1,256 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 26648 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.4.6_amd64.deb ...
Unpacking apt-transport-https (1.4.6) ...
Setting up apt-transport-https (1.4.6) ...
vagrant@stretch:~$ sudo apt-get update
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch Release
Hit:4 http://security.debian.org/debian-security stretch/updates InRelease
Get:1 https://ltb-project.org/debian/jessie jessie InRelease [1,741 B]
Ign:1 https://ltb-project.org/debian/jessie jessie InRelease
Get:6 https://ltb-project.org/debian/jessie jessie/main amd64 Packages [2,903 B]
Fetched 4,644 B in 0s (7,498 B/s)
Reading package lists... Done
W: GPG error: https://ltb-project.org/debian/jessie jessie InRelease: The following signatures were invalid: 3FC3FD92ABA3975D2BEB95A70AC51F926D45BFC5
W: The repository 'http://ltb-project.org/debian/jessie jessie InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
vagrant@stretch:~$ ^C
vagrant@stretch:~$
```

**Comment by coudot** [comment] 2017-06-21 15:00
I think Debian does not accept anymore weak signatures
There is maybe an option in apt to accept them

 I need to create a new GPG key to get rid of these messages

**Comment by plewin** [comment] 2017-06-21 15:02
I just found that.
sha1 is no longer accepted, SHA256 can be used instead
ex http://security.debian.org/debian-security/dists/stretch/updates/InRelease
some people with a similar problem
https://github.com/varnishcache/pkg-varnish-cache/issues/54

**Comment by plewin** [comment] 2017-06-21 15:03
And you don't need to create a new GPG key, just resign the InRelease file.

**Comment by coudot** [comment] 2017-06-21 15:15
Done, can you test?

**Comment by plewin** [comment] 2017-06-21 15:21
It works now 👍 

```
vagrant@stretch:~$ sudo apt-get update
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://deb.debian.org/debian stretch Release
Hit:4 http://security.debian.org/debian-security stretch/updates InRelease
Get:5 https://ltb-project.org/debian/jessie jessie InRelease [1,743 B]
Fetched 1,743 B in 0s (2,004 B/s)
Reading package lists... Done
vagrant@stretch:~$ sudo apt-get install self-service-password
Reading package lists... Done
Building dependency tree
 eading state information... Done
The following additional packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils libapache2-mod-php7.0 libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap libltdl7 liblua5.2-0 libmcrypt4 php php-common php-ldap php-mcrypt php7.0 php7.0-cli php7.0-common
  php7.0-json php7.0-ldap php7.0-mcrypt php7.0-opcache php7.0-readline psmisc ssl-cert
Suggested packages:
  www-browser apache2-doc apache2-suexec-pristine | apache2-suexec-custom php-pear libmcrypt-dev mcrypt
  openssl-blacklist
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils libapache2-mod-php7.0 libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap libltdl7 liblua5.2-0 libmcrypt4 php php-common php-ldap php-mcrypt php7.0 php7.0-cli php7.0-common
  php7.0-json php7.0-ldap php7.0-mcrypt php7.0-opcache php7.0-readline psmisc self-service-password ssl-cert
0 upgraded, 27 newly installed, 0 to remove and 6 not upgraded.
Need to get 7,958 kB of archives.
After this operation, 25.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian stretch/main amd64 libapr1 amd64 1.5.2-5 [96.6 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 libaprutil1 amd64 1.5.4-3 [85.8 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 libaprutil1-dbd-sqlite3 amd64 1.5.4-3 [19.3 kB]
Get:4 http://deb.debian.org/debian stretch/main amd64 libaprutil1-ldap amd64 1.5.4-3 [17.4 kB]
Get:5 http://deb.debian.org/debian stretch/main amd64 liblua5.2-0 amd64 5.2.4-1.1+b2 [110 kB]
Get:6 http://deb.debian.org/debian stretch/main amd64 apache2-bin amd64 2.4.25-3 [1,180 kB]
Get:7 http://deb.debian.org/debian stretch/main amd64 apache2-utils amd64 2.4.25-3 [216 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 apache2-data all 2.4.25-3 [162 kB]
Get:9 http://deb.debian.org/debian stretch/main amd64 apache2 amd64 2.4.25-3 [235 kB]
Get:10 http://deb.debian.org/debian stretch/main amd64 psmisc amd64 22.21-2.1+b2 [123 kB]
Get:11 https://ltb-project.org/debian/jessie jessie/main amd64 self-service-password all 1.0-2 [1,624 kB]
Get:12 http://deb.debian.org/debian stretch/main amd64 php-common all 1:49 [14.1 kB]
Get:13 http://deb.debian.org/debian stretch/main amd64 php7.0-common amd64 7.0.19-1 [868 kB]
Get:14 http://deb.debian.org/debian stretch/main amd64 php7.0-json amd64 7.0.19-1 [17.1 kB]
Get:15 http://deb.debian.org/debian stretch/main amd64 php7.0-opcache amd64 7.0.19-1 [77.2 kB]
Get:16 http://deb.debian.org/debian stretch/main amd64 php7.0-readline amd64 7.0.19-1 [12.2 kB]
Get:17 http://deb.debian.org/debian stretch/main amd64 php7.0-cli amd64 7.0.19-1 [1,289 kB]
Get:18 http://deb.debian.org/debian stretch/main amd64 libapache2-mod-php7.0 amd64 7.0.19-1 [1,231 kB]
Get:19 http://deb.debian.org/debian stretch/main amd64 libltdl7 amd64 2.4.6-2 [389 kB]
Get:20 http://deb.debian.org/debian stretch/main amd64 libmcrypt4 amd64 2.5.8-3.3 [71.2 kB]
Get:21 http://deb.debian.org/debian stretch/main amd64 php7.0 all 7.0.19-1 [48.7 kB]
Get:22 http://deb.debian.org/debian stretch/main amd64 php all 1:7.0+49 [5,016 B]
Get:23 http://deb.debian.org/debian stretch/main amd64 php7.0-ldap amd64 7.0.19-1 [21.0 kB]
Get:24 http://deb.debian.org/debian stretch/main amd64 php-ldap all 1:7.0+49 [5,048 B]
Get:25 http://deb.debian.org/debian stretch/main amd64 php7.0-mcrypt amd64 7.0.19-1 [14.3 kB]
Get:26 http://deb.debian.org/debian stretch/main amd64 php-mcrypt all 1:7.0+49 [5,048 B]
Get:27 http://deb.debian.org/debian stretch/main amd64 ssl-cert all 1.0.39 [20.8 kB]
Fetched 7,958 kB in 1s (6,586 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libapr1:amd64.
(Reading database ... 26680 files and directories currently installed.)
Preparing to unpack .../00-libapr1_1.5.2-5_amd64.deb ...
Unpacking libapr1:amd64 (1.5.2-5) ...
Selecting previously unselected package libaprutil1:amd64.
Preparing to unpack .../01-libaprutil1_1.5.4-3_amd64.deb ...
Unpacking libaprutil1:amd64 (1.5.4-3) ...
Selecting previously unselected package libaprutil1-dbd-sqlite3:amd64.
Preparing to unpack .../02-libaprutil1-dbd-sqlite3_1.5.4-3_amd64.deb ...
Unpacking libaprutil1-dbd-sqlite3:amd64 (1.5.4-3) ...
Selecting previously unselected package libaprutil1-ldap:amd64.
Preparing to unpack .../03-libaprutil1-ldap_1.5.4-3_amd64.deb ...
Unpacking libaprutil1-ldap:amd64 (1.5.4-3) ...
Selecting previously unselected package liblua5.2-0:amd64.
Preparing to unpack .../04-liblua5.2-0_5.2.4-1.1+b2_amd64.deb ...
Unpacking liblua5.2-0:amd64 (5.2.4-1.1+b2) ...
Selecting previously unselected package apache2-bin.
Preparing to unpack .../05-apache2-bin_2.4.25-3_amd64.deb ...
Unpacking apache2-bin (2.4.25-3) ...
Selecting previously unselected package apache2-utils.
Preparing to unpack .../06-apache2-utils_2.4.25-3_amd64.deb ...
Unpacking apache2-utils (2.4.25-3) ...
Selecting previously unselected package apache2-data.
Preparing to unpack .../07-apache2-data_2.4.25-3_all.deb ...
Unpacking apache2-data (2.4.25-3) ...
Selecting previously unselected package apache2.
Preparing to unpack .../08-apache2_2.4.25-3_amd64.deb ...
Unpacking apache2 (2.4.25-3) ...
Selecting previously unselected package psmisc.
Preparing to unpack .../09-psmisc_22.21-2.1+b2_amd64.deb ...
Unpacking psmisc (22.21-2.1+b2) ...
Selecting previously unselected package php-common.
Preparing to unpack .../10-php-common_1%3a49_all.deb ...
Unpacking php-common (1:49) ...
Selecting previously unselected package php7.0-common.
Preparing to unpack .../11-php7.0-common_7.0.19-1_amd64.deb ...
Unpacking php7.0-common (7.0.19-1) ...
Selecting previously unselected package php7.0-json.
Preparing to unpack .../12-php7.0-json_7.0.19-1_amd64.deb ...
Unpacking php7.0-json (7.0.19-1) ...
Selecting previously unselected package php7.0-opcache.
Preparing to unpack .../13-php7.0-opcache_7.0.19-1_amd64.deb ...
Unpacking php7.0-opcache (7.0.19-1) ...
Selecting previously unselected package php7.0-readline.
Preparing to unpack .../14-php7.0-readline_7.0.19-1_amd64.deb ...
Unpacking php7.0-readline (7.0.19-1) ...
Selecting previously unselected package php7.0-cli.
Preparing to unpack .../15-php7.0-cli_7.0.19-1_amd64.deb ...
Unpacking php7.0-cli (7.0.19-1) ...
Selecting previously unselected package libapache2-mod-php7.0.
Preparing to unpack .../16-libapache2-mod-php7.0_7.0.19-1_amd64.deb ...
Unpacking libapache2-mod-php7.0 (7.0.19-1) ...
Selecting previously unselected package libltdl7:amd64.
Preparing to unpack .../17-libltdl7_2.4.6-2_amd64.deb ...
Unpacking libltdl7:amd64 (2.4.6-2) ...
Selecting previously unselected package libmcrypt4.
Preparing to unpack .../18-libmcrypt4_2.5.8-3.3_amd64.deb ...
Unpacking libmcrypt4 (2.5.8-3.3) ...
Selecting previously unselected package php7.0.
Preparing to unpack .../19-php7.0_7.0.19-1_all.deb ...
Selecting previously unselected package php.
Preparing to unpack .../20-php_1%3a7.0+49_all.deb ...
Unpacking php (1:7.0+49) ...
Selecting previously unselected package php7.0-ldap.
Preparing to unpack .../21-php7.0-ldap_7.0.19-1_amd64.deb ...
Unpacking php7.0-ldap (7.0.19-1) ...
Selecting previously unselected package php-ldap.
Preparing to unpack .../22-php-ldap_1%3a7.0+49_all.deb ...
Unpacking php-ldap (1:7.0+49) ...
Selecting previously unselected package php7.0-mcrypt.
Preparing to unpack .../23-php7.0-mcrypt_7.0.19-1_amd64.deb ...
Unpacking php7.0-mcrypt (7.0.19-1) ...
Selecting previously unselected package php-mcrypt.
Preparing to unpack .../24-php-mcrypt_1%3a7.0+49_all.deb ...
Unpacking php-mcrypt (1:7.0+49) ...
Selecting previously unselected package ssl-cert.
Preparing to unpack .../25-ssl-cert_1.0.39_all.deb ...
Unpacking ssl-cert (1.0.39) ...
Selecting previously unselected package self-service-password.
Preparing to unpack .../26-self-service-password_1.0-2_all.deb ...
Unpacking self-service-password (1.0-2) ...
Setting up libapr1:amd64 (1.5.2-5) ...
Setting up psmisc (22.21-2.1+b2) ...
Setting up apache2-data (2.4.25-3) ...
Setting up ssl-cert (1.0.39) ...
Processing triggers for libc-bin (2.24-11) ...
Setting up libaprutil1:amd64 (1.5.4-3) ...
Setting up php-common (1:49) ...
Created symlink /etc/systemd/system/timers.target.wants/phpsessionclean.timer ÔåÆ /lib/systemd/system/phpsessionclean.ti
mer.
Processing triggers for systemd (232-25) ...
Setting up libltdl7:amd64 (2.4.6-2) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up liblua5.2-0:amd64 (5.2.4-1.1+b2) ...
Setting up php7.0-common (7.0.19-1) ...

Creating config file /etc/php/7.0/mods-available/calendar.ini with new version

Creating config file /etc/php/7.0/mods-available/ctype.ini with new version

Creating config file /etc/php/7.0/mods-available/exif.ini with new version

Creating config file /etc/php/7.0/mods-available/fileinfo.ini with new version

Creating config file /etc/php/7.0/mods-available/ftp.ini with new version

Creating config file /etc/php/7.0/mods-available/gettext.ini with new version

Creating config file /etc/php/7.0/mods-available/iconv.ini with new version

Creating config file /etc/php/7.0/mods-available/pdo.ini with new version

Creating config file /etc/php/7.0/mods-available/phar.ini with new version

Creating config file /etc/php/7.0/mods-available/posix.ini with new version

Creating config file /etc/php/7.0/mods-available/shmop.ini with new version

Creating config file /etc/php/7.0/mods-available/sockets.ini with new version

Creating config file /etc/php/7.0/mods-available/sysvmsg.ini with new version

Creating config file /etc/php/7.0/mods-available/sysvsem.ini with new version

Creating config file /etc/php/7.0/mods-available/sysvshm.ini with new version

Creating config file /etc/php/7.0/mods-available/tokenizer.ini with new version
Setting up libmcrypt4 (2.5.8-3.3) ...
Setting up libaprutil1-ldap:amd64 (1.5.4-3) ...
Setting up php7.0-ldap (7.0.19-1) ...

Creating config file /etc/php/7.0/mods-available/ldap.ini with new version
Setting up php7.0-readline (7.0.19-1) ...

Creating config file /etc/php/7.0/mods-available/readline.ini with new version
Setting up php7.0-opcache (7.0.19-1) ...

Creating config file /etc/php/7.0/mods-available/opcache.ini with new version
Setting up libaprutil1-dbd-sqlite3:amd64 (1.5.4-3) ...
Setting up apache2-utils (2.4.25-3) ...
Setting up apache2-bin (2.4.25-3) ...
Setting up php7.0-mcrypt (7.0.19-1) ...

Creating config file /etc/php/7.0/mods-available/mcrypt.ini with new version
Setting up php-ldap (1:7.0+49) ...
Setting up php7.0-json (7.0.19-1) ...

Setting up php-mcrypt (1:7.0+49) ...
Setting up apache2 (2.4.25-3) ...
Enabling module mpm_event.
Enabling module authz_core.
Enabling module authz_host.
Enabling module authn_core.
Enabling module auth_basic.
Enabling module access_compat.
Enabling module authn_file.
Enabling module authz_user.
Enabling module alias.
Enabling module dir.
Enabling module autoindex.
Enabling module env.
Enabling module mime.
Enabling module negotiation.
Enabling module setenvif.
Enabling module filter.
Enabling module deflate.
Enabling module status.
Enabling module reqtimeout.
Enabling conf charset.
Enabling conf localized-error-pages.
Enabling conf other-vhosts-access-log.
Enabling conf security.
Enabling conf serve-cgi-bin.
Enabling site 000-default.
Created symlink /etc/systemd/system/multi-user.target.wants/apache2.service ÔåÆ /lib/systemd/system/apache2.service.
Created symlink /etc/systemd/system/multi-user.target.wants/apache-htcacheclean.service ÔåÆ /lib/systemd/system/apache-h
tcacheclean.service.
Setting up php7.0-cli (7.0.19-1) ...
update-alternatives: using /usr/bin/php7.0 to provide /usr/bin/php (php) in auto mode
update-alternatives: using /usr/bin/phar7.0 to provide /usr/bin/phar (phar) in auto mode
update-alternatives: using /usr/bin/phar.phar7.0 to provide /usr/bin/phar.phar (phar.phar) in auto mode

Creating config file /etc/php/7.0/cli/php.ini with new version
Setting up libapache2-mod-php7.0 (7.0.19-1) ...

Creating config file /etc/php/7.0/apache2/php.ini with new version
Module mpm_event disabled.
Enabling module mpm_prefork.
apache2_switch_mpm Switch to prefork
apache2_invoke: Enable module php7.0
Setting up php7.0 (7.0.19-1) ...
Setting up php (1:7.0+49) ...
Setting up self-service-password (1.0-2) ...
Processing triggers for libc-bin (2.24-11) ...
Processing triggers for systemd (232-25) ...
vagrant@stretch:~$
```

**Comment by coudot** [comment] 2017-06-21 15:24
Great, so I close the issue. Thanks for the tests and the provided links.

**Closed by coudot** 2017-06-21 15:24 UTC
Labels: packaging

**Comment by plewin** [comment] 2017-06-21 15:42
Note,
Some php modules are no longer built-ins, extra steps may be required if the associated packages are not already installed.

```
sudo apt-get install php-xml php-mbstring
systemctl reload apache2
```

**Comment by sgargel** [comment] 2017-06-22 08:35
Thanks. Can the repo name and [documentation](https://ltb-project.org/documentation/self-service-password/latest/install_debian) be updated in something that can not be misunderstood?  Perhaps `s/jessie/stable/g` ?

**Comment by plewin** [comment] 2017-06-24 11:38
I believe listing the ubuntu/debian versions where the installation procedure is supported or tested would be better.
