### ISSUE TITLE
Reset token validation issue

### ISSUE THREAD

**Issue by lucamaro** [ltb-project/self-service-password#128] opened 2017-07-25 07:54 UTC
Hi all,
I have trouble in reset password via email, basically the token is never considered valid because user session variables (login and time) are not saved to disk (session file is empty). Enabling error_reporting with E_ALL the page says:

`Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/html/index.php:155) in /var/www/html/pages/sendtoken.php on line 149`

Is there a problem or I'm missing something? BTW I tried ssp v1.0, but it seems to me that master branch has the same behaviour.

Thank you for this great work.
Luca

**Comment by lucamaro** [comment] 2017-07-26 14:05
So, after some work I confirm that the problem is due to session_start in sendtoken.php called after the beginning of html page, as the error message asserts.

With some changes I got it working, if you want I can submit a PR. But some of the logic about token/session inside sendtoken.php has to be moved into index.php.

Let me know.
Luca

**Comment by plewin** [comment] 2017-08-09 23:26
Hi @lucamaro, thank you for posting this.

I acknowledge that the code dealing with the sessions/tokens has some problems like being difficult to understand and producing unnecessary alarming logs but it should work.

Would you mind posting a link to the commit/branch working for you and posting your phpinfo details on a github gist ?

**Comment by lucamaro** [comment] 2017-08-10 06:49
Hi @plewin,
here is [phpinfo](https://gist.github.com/lucamaro/459585a53522a2cb49d4d9d5278f1939) and here a super minimal change to [index.php](https://github.com/lucamaro/self-service-password/commit/2065f6f5d1b7fe4686bef8f316c2b2cb68637874) that's working for me.

Without this change session files are always empty, so no session data is saved and reset token page says that the token is not valid.

Thank you!
Luca

**Comment by coudot** [comment] 2017-08-16 13:50
I don't see why the current code fails. We use the ini_set calls just before calling cookies method. Maybe there are other cookies used in the application (set by a reverse proxy in front of SSP) which could explain why it fails?

**Comment by lucamaro** [comment] 2017-08-17 06:14
I'm using docker with a custom [lucamaro/ltb-self-service-password](https://hub.docker.com/r/lucamaro/ltb-self-service-password/) based on standard php:7-apache, no reverse proxy in front of it.

I tried [moss/selfservicepassword](https://hub.docker.com/r/moss/selfservicepassword/) that is based on php:7-fpm and nginx as reverse proxy and it does not have the same problem. 

Which setup do you suggest? 

BTW, start_session documentation has the following note:

>     Note:
>     To use cookie-based sessions, session_start() must be called before outputing anything to the browser.

Does it make sense to you? Perhaps fpm is more permissive than apache module?

**Comment by coudot** [comment] 2017-08-17 07:39
Good question. But I use a standard installation with Apache and it works well. There must be something that print something before the session_start() call but I don't see what.

**Comment by plewin** [comment] 2017-08-17 07:47
Everything from
https://github.com/ltb-project/self-service-password/blob/master/index.php#L165 to https://github.com/ltb-project/self-service-password/blob/master/index.php#L216 is printed before https://github.com/ltb-project/self-service-password/blob/master/pages/sendtoken.php session_start 

I will try the failing docker image later to see if i can spot something

**Comment by coudot** [comment] 2017-08-17 07:54
Hum, the output_buffering ini_set should work for this, but seems it is ignored in some cases. See https://stackoverflow.com/questions/6807742/php-output-buffering-ini-option-is-ignored#9434352

On my laptop, the ini_set seems to work well.

**Comment by plewin** [comment] 2017-08-20 14:18
I reproduced and I confirm the bug on @lucamaro's docker image.
I still need to dig deeper to fully understand what's happening.

**Comment by lucamaro** [comment] 2017-08-30 20:44
Hi @plewin, @coudot,
thank you for the time spent for explaining and reproducing this issue.

I made some tries and found that output_buffering runtime config is changeble only in mode PHP_INI_PERDIR. So I tried setting the variable in global php.ini:

    root@cf279e1fdba7:/var/www/html# cat /usr/local/etc/php/php.ini
    output_buffering = On

Now session file contains login stuff and reset by token is working. 

Do you think it could be a valid solution?

**Comment by plewin** [comment] 2017-08-30 21:13
yes it seems to me that the line https://github.com/ltb-project/self-service-password/blob/v1.0/index.php#L59 is useless / has no effects since php 5.3.
According to this https://stackoverflow.com/questions/14867407/php-ini-set-changes-dont-take-with-safe-mode-off

I did not try to touch to the php.ini but in my experiments, I found this potential solution :

I comment this line and I put an ob_start() here
https://github.com/ltb-project/self-service-password/blob/v1.0/index.php#L59
I put an ob_end_flush ()
https://github.com/ltb-project/self-service-password/blob/v1.0/index.php#L152

I tried it works for me on your docker but I am not 100% sure that no side effects are generated, I didn't test the sms feature with that.

I am still puzzled by this issue, why it works elsewhere.

**Comment by lucamaro** [comment] 2017-08-30 21:29
Ok, in the meantime I'll modify my image with php.ini as a workaround, since the instance is dedicated to this service and session are always used in the same mode.

**Comment by plewin** [comment] 2017-08-30 23:08
I think I solved the mystery.

SSP requires that output_buffering ~ >= 3500 to work.
3500 because it is approximately the number of bytes output by php from the beginning to the session_start https://github.com/ltb-project/self-service-password/blob/master/pages/sendtoken.php#L156

On a fresh centos 6 and debian wheezy + apache + SSP output_buffering is configured with the distro's php init with output_buffering = 4096.

the ini_set("output_buffering", 0) is useless and misleading. it does not disable the output_buffering which is by the way required.

Docker php 7 + apache do no ship a php.ini and use the default value output_buffering = 0 this is why it does not work.

moss' docker image works but it uses php 7 + fpm, I believe the docker image for fpm use a php.ini with a output_buffering set.

I will confirm this tomorrow. if it is true, SSP has a bug and setting output_buffering = On is not the correct solution because it is only by chance that ssp works with 4096. SSP need to be refactored to not display anything before the session_start or use the ob_* functions.

**Comment by coudot** [comment] 2017-08-31 08:38
Hi @plewin, I removed the ini_set in our code and set a comment in sample Apache configuration as a first simple workaround.

The other workaround is indeed to `ob_start()` and `ob_end_flush()` in `index.php` but as you said I don't know if will not break something else.

Rewriting the code is indeed the best solution, and for me this is linked to the use of a framework like Smarty, were all business code is processed before page display. But I don't think we can do that for 1.1.

**Comment by coudot** [comment] 2017-08-31 16:28
@plewin could we close this issue for 1.1 milestone and maybe open a new one to find a better workaround?

**Comment by plewin** [comment] 2017-08-31 16:47
Not yet, I have new information about this issue and I am currently compiling them.

**Comment by plewin** [comment] 2017-08-31 18:22
I found the root cause of the change of behavior,

I tried moss' docker image of SSP (1.0) and it works fine (image based on php-fpm). I verified the phpinfo and surprisingly to me the php session/cookies/output_buffering settings are 100% same as lucamaro's image. output_buffering = 0

output_buffering = 0 and the bug is not present. I also found another thing surprising, var_dump(session_start()) gives true for one docker and false for the other.

So I suspected that the implementation of sessions was different between php-fpm et php for apache. I looked php's source code and found no evidence of difference of behavior for sessions between fpm and mod for apache.

I noticed that the two versions of php in the dockers were differents (7.0.13 vs 7.1.8), so tried to compare them on github.
https://github.com/php/php-src/compare/PHP-7.0.13...PHP-7.1.8#diff-52eb9eb7f9d5d9125fbb1337a6541c06

I spend a lot of time trying to find something that changes something relevant to us and I found something interesting near the code that generates our error "Cannot send session cache limiter - headers already sent"

https://github.com/php/php-src/compare/PHP-7.0.13...PHP-7.1.8#diff-52eb9eb7f9d5d9125fbb1337a6541c06L1331

Between these 2 php versions a new call was added php_session_abort(); if the headers cannot be sent.
It looks to me that the php_session_abort change the state of the session and closes the data.
https://github.com/php/php-src/compare/PHP-7.0.13...PHP-7.1.8#diff-52eb9eb7f9d5d9125fbb1337a6541c06R1552

I assume that in the latest versions of php, if we get the "Cannot send session cache limiter - headers already sent" the session is destroyed ?



I think I understand how this change of behavior happened in php.


This commit was made in Jan 12, 2016 so session_start() do not return true when headers cannot be send.
https://github.com/php/php-src/commit/a15e9ccba8a34553c029fb4574edba87c76447e5#diff-52eb9eb7f9d5d9125fbb1337a6541c06R1294

The line was changed to "php_session_abort();" between then and now by a refactor maybe ?

I could not find this change of behavior in any 5.x, 7.0.x branches or older, it is since here exactly since 7.1.0

I somehow found this, it seems to be an intentional change (but it is not really clear) https://github.com/php/php-src/pull/2150#issuecomment-252968003

And UPGRADING note has been added

> session_start() returns FALSE and no longer initializes $_SESSION when
>     it failed to start session.

So our users affected are users of SSP on php >= 7.1 with output_buffering = 0 (<= ~ 3500)

The only solution is to not send headers using the methods discussed ealier.

Now that I understand how it works, I am confident that implementing the ob_start() and 
ob_end_flush() solution should not have side effects and that it is what we should do for 1.1. I will submit a PR.

**Comment by coudot** [comment] 2017-09-01 08:53
Fixed by @plewin in #146

**Closed by coudot** 2017-09-01 08:53 UTC
Labels: bug
