### ISSUE TITLE
reCAPTCHA not working on master

### ISSUE THREAD

**Issue by rwwest7** [ltb-project/self-service-password#175] opened 2018-01-03 21:08 UTC
Fresh install. 

The reCAPTCHA image doesn't show up on the form, but when I try to submit it tells me I did not answer the reCAPTCHA.

I think I'm using ver. 2.0 but only see docs for version 1.1 and below. Is the setup the same?

**Comment by plewin** [comment] 2018-01-03 21:20
Hi @rwwest7 

Latest SSP release is version 1.1.
https://ltb-project.org/documentation/self-service-password/1.1/start

How did you install SSP ?

**Comment by rwwest7** [comment] 2018-01-03 23:08
I downloaded from Github, uploaded to web server and edited the config file.


I assumed 2.0 was the newest because on https://github.com/ltb-project/self-service-password, the drop down has "1.1, 1.0, 2 and Master"


Is there a preferred installation method over downloading from Github?



________________________________

**Comment by rwwest7** [comment] 2018-01-03 23:20
I downloaded 1.1 from here: https://ltb-project.org/archives/


Deleted my entire directory, uploaded from above, used my exact same config.inc.php file and it works now.


Something wrong with the github files?


________________________________

**Comment by plewin** [comment] 2018-01-04 02:22
@rwwest7 

To download packages
https://ltb-project.org/download#self_service_password

To get stable versions from github, use the tags v1.0 v1.1, when a stable version is released, the commit used for the package is tagged

Branches:

* _master_, will be released as 1.2 or 2.0 if 2.0-proposal get merged
* _2.0-proposal_, major changes currently in development and discussion that will potentially be merged into master (i just renamed from 2.0 to make it clear that it is not accepted currently)
master should be stable enough for testing but I know there is 2 regressions since the integration of twig, the captcha does not show because of couple missing lines and there is a field in changebytoken IIRC that appears editable when it should not. I am not sure yet if I should fix it now, submit a PR to revert twig integration because the refactor needed to reorganise the templates and make twig really useful is now postponed to 2.0-proposal, or just wait 2.0-proposal to get merged because the fix is already in it.
* _1.1_ branch just in case we have to release new packages with an urgent fix, e.g. 1.1.1 ?
* _1.0_

I keep the issue open as a reminded that this must be fixed.

**Comment by plewin** [comment] 2018-01-10 18:21
I am closing this issue because master got fixed.

**Closed by plewin** 2018-01-10 18:21 UTC
Labels: bug
