### ISSUE TITLE
SMS token send is not triggered when browser is Spanish

### ISSUE THREAD

**Issue by stromvirvel** [ltb-project/self-service-password#221] opened 2018-07-12 09:44 UTC
When the browser is Spanish or language was changed to Spanish using an addon, the SMS token send is not being triggered. This happened to me when using Chrome 67 on macos. When browser language was set to German or English, the SMS token sender was triggered correctly.

I'm running nginx and php7.1.
https://github.com/mimacom/ansible-role-selfservice/blob/master/tasks/main.yml

**Comment by moepot** [comment] 2018-07-12 09:49
This happens with self service password v1.1 and v1.3

**Comment by moepot** [comment] 2018-07-12 10:24
As a workaround, I set the setting `$allowed_lang = array('en')`

**Comment by coudot** [comment] 2018-07-12 21:10
I don't reproduce the issue, could you try to set debug mode and see what happens?

**Comment by moepot** [comment] 2018-07-30 11:33
The chrome extension is called `Quick Language Switcher` version 0.0.0.4.
We have users in Spain who have their OS set to `es-es` and they are affected by that bug aswell.

I will try to reproduce the bug in debug mode, but I guess I can manage it by the end of August.

**Comment by plewin** [comment] 2018-07-30 22:12
I could not reproduce the bug on chrome + quick language switcher + switched to spanish.
Is that possible that your issue come from the $sms_attribute in your ldap directory ? Maybe your spanish users have a sms attribute in a format that is not recognized by self service password ? Or it worked for a single given user in German and English but not in Spanish ?

**Comment by plewin** [comment] 2020-01-20 21:01
Thank you, I'm closing this issue, it can't be reproduced. Probably a config or browser extension issue.

**Closed by plewin** 2020-01-20 21:01 UTC
Labels: invalid
